name: Build, Scan & Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - index.js
      - .github/workflows/docker-build-and-scan.yml

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: 1.0.${{ github.run_number }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Enable Docker Content Trust
        run: echo "DOCKER_CONTENT_TRUST=1" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image with versioned tag
        run: |
          docker build -t $IMAGE_REGISTRY/$IMAGE_NAME:${IMAGE_TAG} .
          docker tag $IMAGE_REGISTRY/$IMAGE_NAME:${IMAGE_TAG} $IMAGE_REGISTRY/$IMAGE_NAME:latest

      - name: Run Hadolint (Dockerfile Linter)
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-check
          level: warning

      - name: Run Dockle (Docker Config Scan)
        uses: erzz/dockle-action@v1
        with:
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Run Trivy (Vulnerability Scan)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push Docker Image to GHCR
        run: |
          export DOCKER_CONTENT_TRUST=0
          docker push $IMAGE_REGISTRY/$IMAGE_NAME:${IMAGE_TAG}
          docker push $IMAGE_REGISTRY/$IMAGE_NAME:latest