name: Build, Scan & Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - index.js
      - .github/workflows/docker-build-and-scan.yml

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      # --- Static Dockerfile Lint ---
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3
        with:
          dockerfile: Dockerfile

      # --- Scan Docker Image Config ---
      - name: Run Dockle (Docker image best practices)
        uses: erzz/dockle-action@v1
        with:
          image: ${{ env.IMAGE_NAME }}:latest

      # --- Vulnerability Scanner ---
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@v0.18.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: table
          exit-code: 0
          ignore-unfixed: true

      - name: Push Image to GHCR
        run: |
          docker push $IMAGE_NAME:latest